version: "3"

services:
  tasks-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cshade/node-tasks-api
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    links:
      - mongo
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"
